### ISSUE TITLE
Create a php endpoint which returns a JSON dictionary of dictionaries for all required vocabularies

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#106]
Each sea-map needs to list all the vocabularies it requires and which language it wants to use. English is the default.

See (https://github.com/SolidarityEconomyAssociation/sea-map/issues/104)

Create a new php endpoint which take the new config file info specified above and returns a dictionary of dictionaries of the terms in these vocabularies in JSON. 

So that John can get on with his side of things, and to help with the spec, the first thing we should do here is hard code the script to return place holder dictionaries.

**Comment by wu-lee** [comment]
@King-Mob - I've pushed a stub script to the branch `sm106-vocab-api`.
- Cherry-pick or otherwise integrate it.
- Add a suitable `vocabs.json` file to `/config/` in your sea-map `/ext/` map site, 
- and `npm run rebuild; npm run server`

Then the URL with path `/services/get_vocabs.php` should return whatever's in it as content-type `application/json`. You can use it to test against (but don't commit it to git). 

My currently suggested content is [here][1], but see discussion at https://github.com/SolidarityEconomyAssociation/sea-map/issues/104#issuecomment-777890839

[1]: https://gist.github.com/wu-lee/af0618d567e5235b21dbd5fdd2674075#file-vocabs2-json
