### ISSUE TITLE
Facebook links missing from some maps

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#110]
https://prod.data.solidarityeconomy.coop/sea-lod/mersey-green/303.html
has a facebook entry, but it's not visible in its dialog.

**Comment by ColmMassey** [comment]
"No, it's the query. No Facebook field. Also, creates duplicate results..." from chat @wu-lee

**Comment by wu-lee** [comment]
See also https://github.com/SolidarityEconomyAssociation/covid-mutual-aid-project/issues/1#issuecomment-756931631

**Comment by ColmMassey** [comment]
Can we address the specific symptom highlighted in this Issue just by fixing the query?

**Comment by wu-lee** [comment]
I think we can address it either in the query or the data generation. In either case, it should normalise the value into a Facebook path, dropping those which can't be.  I see currently the query does something like this:

```
   OPTIONAL {
        ?uri foaf:account ?accountf .
        ?accountf foaf:accountServiceHomepage "https://facebook.com/" .
        ?accountf foaf:accountName ?facebook .
    }
```

But I think it's easier to do a thorough job in the Ruby code.

**Comment by wu-lee** [comment]
Ok, so the `limesruveycore.rb` code shared by the Mersey, Newbridge, deep-adaptation, and Oxford datasets has been modified to use the Facebook URL normalisation used on the Covid Mutual Aid project, and pushed to `dev` so that the data is regenerated with these by the cron job.

The Oxford map site queries has terms for `facebook` and `twitter` terms already, but the others were missing these, so I've added them back in and redeployed on their `dev` versions (Note that the Twitter normalisation has not been inspected in detail or changed, however those map links I have checked seem ok.)

- https://dev.mersey-green.solidarityeconomy.coop/
- https://dev.maps.solidarityeconomy.coop/newbridge/map.html
- https://dev.oxford.solidarityeconomy.coop/map.html

Covid Mutual Aid already addressed as mentioned in https://github.com/SolidarityEconomyAssociation/covid-mutual-aid-project/issues/1

The new Mutual Aid data has a `Facebook` field (but no `Twitter` field), which should appear if present, but this is work in progress and part of https://github.com/SolidarityEconomyAssociation/covid-mutual-aid-project/issues/2

ICA/ICA-Youth and DotCoop data does not have populate the `Facebook` field (there is just a catch-all `Website` field), so nothing to do there.  Likewise Coops UK, I think, if we were maintaining that.
