### ISSUE TITLE
Korean language support

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#126]
Extend sea-map to support non latin languages, using Korean as an example.

**Comment by ColmMassey** [comment]
Do we still need to do any plumbing before we can support non latin langages in our Linked Data publication as well as in sea-map? @King-Mob @wu-lee ?

**Comment by wu-lee** [comment]
> Do we still need to do any plumbing before we can support non latin langages in our Linked Data publication as well as in sea-map? @King-Mob @wu-lee ?

Without looking at the code, I'd say quite possibly, yes.  Are you including languages which don't write left-to-right, like Arabic? Korean, so far as I know, can go left-to-right, when it's not top-top-bottom.

Other than that, I would guess it's an issue of complete Unicode support, which doesn't always Just Work, because encodings can trip you up.

**Comment by ColmMassey** [comment]
I can see some Korean text in the spreadsheet. Are you happy for me to ask ICA to start to populate it now? @King-Mob?

**Comment by King-Mob** [comment]
Yes please

**Comment by wu-lee** [comment]
I've deployed a Korean-enabled version of the ica-project. You can view it here:

https://dev.ica.solidarityeconomy.coop/?language=KO

Note that it's loading Spanish, French and English vocab terms as well, and this seems to mean the vocab loading takes about 30 seconds!  Even though there are not any actual Korean tranlations for the vocabs yet.

**Comment by ColmMassey** [comment]
>Note that it's loading Spanish, French and English vocab terms as well,
Do you mean it has to always load all supported vocabularies? Is this becasue if a korean term is missing it needs to use the default?

Regardless I think we need to take a look at this with an optimisation lense and get those load times down to something managable. Hopefully there will be a few easy changes that could speed it up.

**Comment by wu-lee** [comment]
See https://github.com/SolidarityEconomyAssociation/sea-map/issues/133

**Comment by wu-lee** [comment]
Also https://github.com/SolidarityEconomyAssociation/sea-map/issues/134

**Comment by King-Mob** [comment]
review here: https://dev.ica.solidarityeconomy.coop/?language=KO

**Comment by wu-lee** [comment]
DotCoop map updated to sea-map 1.x and se-open-data 2.x (so ESSGLOBAL 2.1)

Korean, Spanish, and French translations added for about panel, and country names.

https://dev.dotcoop.solidarityeconomy.coop/?language=KO
https://dev.dotcoop.solidarityeconomy.coop/?language=FR
https://dev.dotcoop.solidarityeconomy.coop/?language=ES

**Comment by wu-lee** [comment]
ICA Youth Network already on sea-map 1.x and ESSGLOBAL 2.1, but data regenerated to get new country translations, and FR, ES, KO localisations added:

https://dev.ica-youth-network.solidarityeconomy.coop/?language=KO
https://dev.ica-youth-network.solidarityeconomy.coop/?language=FR
https://dev.ica-youth-network.solidarityeconomy.coop/?language=ES

**Comment by wu-lee** [comment]
ICA map (see above) had some sort of error with KO, redeployed and now it seems to be ok witn KO (possibly an older version?)

**Comment by wu-lee** [comment]
Activities and org-stucture vocabs still not available in KO for ICA or ICA Youth.

I'm going away on a long weekend trip tomorrow afternoon, back Sunday, so I may or may not get to fix that.

If not, and @King-Mob gets the time to add Korean translations to the vocabs in `map-sse` under `vocabs/standard/*.ttl`, the method to redeploy any updated vocabs is:

- check out map-sse project, `ica10-draft-locality-vocabs` branch
- Ruby toolchain needed, plus `raptor`, `rsync`, `bash`, Unix command-line usuals
- `cd generators/`
- `./build 2.1-dev`
- `./deploy generated/2.1 dev-1:/var/www/vhosts/vocabs.solidarityeconomy.coop/www/essglobal/2.1`

However the ica data needs to be rebuilt to get these live on the site. This is how (although untested in full):
- check out the `open-data` project
- check out the `password-store` project adjacent to it
- Ruby toolchain needed etc. as above, plus `gpg` v2
- `git checkout dev`
- copy `ica-2021-10-11.csv` from the `ICA/ica-data` directory on NextCloud as `ica/original-data/original.csv`
- rename the second `Country` header to `Country-address` (this is an ICA quirk we'd like to eradicate, we don't want duplicate column headers)
- `cd ica`
- `../../password-store/env-setup`
- `bundle install`
- `bundle exec seod convert`
- `bundle exec seod generate`
- `bundle exec seod deploy`
- `bundle exec seod triplestore`

The `password-store` is possibly a point where you may run into problems, because you may need your GnuPG keychain set up, and have imported all the public keys in `keys/`. There are instructions in the repo, I think they are complete.

**Comment by ColmMassey** [comment]
Search is broken in Korean version, so returning it to In Progress at the top of the list.

**Comment by King-Mob** [comment]
@ColmMassey This was because we have 1 korean vocab (countries) but no other ones. The code was assuming that if we had 1 set of vocabs then we had all 6. I've changed that to be applied per vocab now, so the dropdowns can be in mixed languages.

**Comment by King-Mob** [comment]
up on the dev site: https://dev.ica.solidarityeconomy.coop/?language=KO

**Comment by ColmMassey** [comment]
Drop downs in Korean search now working again. :-)

**Comment by ColmMassey** [comment]
It's not clear why some terms have Korean translations and some not. This spreadsheet should be the primary source for translations.
https://nextcloud.solidarityeconomy.coop/index.php/apps/onlyoffice/s/i8dNYqbmj7MXrax

I note also that some of the French and Spanish terms have been translated in the app, but not copied into the spreadsheet. Can we realingn them? Perhaps ask @tomdavidson so he can get familiar with how we are managing mutlilingual data?

**Comment by ColmMassey** [comment]
I've gotten a Korean friend to finish the translations! They are in the spreadsheet. Can you use these ones now? So we need them on ICA, Dotcoop and ICA Youth, in that order of impotance on dev. Signal me, so I can test them ASAP before we push to prod.
@wu-lee were there any issues with the Korean on the Dotcoop site?

**Comment by tomdavidson** [comment]
@ColmMassey  the wrong tom but thanks for bringing solidarityeconomy.coop to my attention - way cool.

**Comment by wu-lee** [comment]
> were there any issues with the Korean on the Dotcoop site?

Not to my knowledge - the drop downs work, presumably because there is only one vocab and that's got Korean.

**Comment by ColmMassey** [comment]
Getting 

> It's not clear why some terms have Korean translations and some not. This spreadsheet should be the primary source for translations. https://nextcloud.solidarityeconomy.coop/index.php/apps/onlyoffice/s/i8dNYqbmj7MXrax
> 
> I note also that some of the French and Spanish terms have been translated in the app, but not copied into the spreadsheet. Can we realingn them? Perhaps ask @tomdavidson so he can get familiar with how we are managing mutlilingual data?

@ThomasDavisonsGit

**Comment by ColmMassey** [comment]
@King-Mob When can you get the new Korean translations into the ICA maps?

**Comment by King-Mob** [comment]
I'm working on it now. Should be up in ten minutes

**Comment by King-Mob** [comment]
New translations are in the ICA map. Working on Dotcoop and ICA Youth now

**Comment by ColmMassey** [comment]
There still seems to be lots of areas that are using English terms.

**Comment by ColmMassey** [comment]
Pretty comprehensive!

**Comment by ColmMassey** [comment]
I don't think we could use it to get translations from third parties though. How should we do that?

**Comment by wu-lee** [comment]
Well, we could remove or hide the parts with no translation required? (The bits which inherently have no localisation, and maybe also the bits with no localisation needed from the 3rd party in question.)

That would need to be manual initially, I'm not sure of the scope for automating that in an OnlyOffice spreadsheet. Some sort of web UI might be better for automating that.

**Comment by ColmMassey** [comment]
I think a few manual steps are fine. Let's test with the last tweaks of the Korean translations.

**Comment by wu-lee** [comment]
@ColmMassey - looks like this should be closed?

**Comment by ColmDC** [comment]
> @ColmMassey - looks like this should be closed?

Is it not closed already?
