### ISSUE TITLE
Entering and leaving search 'mode'

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#14]
There are a few confusing transistions that happen when moving between using search and other methods of navigating.

### Initiating Search
There are 2 ways of initiating a search.
1) Typing text into the box and hitting return
2) Selecting the "Show Search History icon in the main panel"

I think we need to do the following:

1. Change the title Search History to simply Search.
1. Mirror the Search dialog box, in the Search panel. 
1. The user can choose to type, in either. As text is typed/edited in one, it is mirrored in the other.
1. When in any of the other panels and the Search panel is selected, a search is not initiated straight away, but an empty search dialog is presented. No changes to marker visibilitys, zooming or panning takes place yet. The user can then: 
  1. choose to type and submit a new search term. The search is conducted and the results presented below in [alphabetical order](https://github.com/SolidarityEconomyAssociation/sea-map/issues/13). 
  1. or, if there are searches in the stack, to select the back button and repeat the last search conducted. Once that search has been repeated the user can chose to 
    a) move backwards or forwards in the search stack using the arrow icons, or 
    b) edit the current contents of the dialog box and submit a fresh search request. This new search is appended to the END of the search stack, (see [here](https://github.com/SolidarityEconomyAssociation/sea-map/issues/11)). 
1. If a new search term is entered in the dialog on the map, the Search panel is opened with the Search dialog prepopulated with that search term and the search is carried out. This search is appended to the end of the stack. After the search returns, the user has the option to enter a new search in the panel or hit the back arrow and repeat the previous search; 

### Returning to Directory
When changing panels using any of the panel tabs the user:
1.  there should be no change of zoom/pan or the visible marker set, but any open dialog bubbles are closed. 
1. when the user selects the "Show directory" tab:
  1. and no search has been submitted since the last time the Directory was open, the Directory panels should open as they were, the last time the user was there. Only when a panel option is selected, should there be any auto panning, zooming or changes make to visible marker;
  1. and there has been a search conducted since the last time the Directory was open, only the top Directory panel should open; (Otherwise there will be a disconnect between the co-ops visible on the map and those available for selection in the panel.)

**Comment by dtmakm27** [comment]
I think it's not a bad idea,
Though I suggest we Illustrate it first using the same process Joe used for making suggestions and visualising them. (what was the name of the illustrator tool?)
We will most-likely find that the flow goes bad somewhere and it's easier to find it here and now rather than re-coding it later.

Thoughts, would you be happy if i were to do that?
It would also help with making sure we are both talking about the same things

**Comment by ColmMassey** [comment]
Joe's application was called sketch.cloud

**Comment by ColmMassey** [comment]
I agree that it might speed things up, and ensure we understand each other. Will also be good to be proficient at using it for mock ups for future versions/concepts.

**Comment by dtmakm27** [comment]
Definitely

I'll do one today

**Comment by ColmMassey** [comment]
Mighr be able to access some of Joe's resources [here](https://sketch.cloud/s/75lep).

**Comment by dtmakm27** [comment]
Thinking about it, mirroring the search box is the only thing that we have to think whether we should do.

![Screenshot from 2020-03-23 12-27-26](https://user-images.githubusercontent.com/34026440/77324046-1bb46b80-6d0e-11ea-8ba6-6b71beb86f0e.png)

(The actual search field won't be just a ugly copy paste :) )

Basically it's the same as it is now but you only start searching when you press search/enter in either of the boxes (instead of when you go into the search panel)

It's also related with this issue: https://github.com/SolidarityEconomyAssociation/sea-map/issues/6
To solve this one we could just remove the big search (the one outside of the search tab) and leave out only the one inside the search tab



So for mobile we can have 
![Screenshot from 2020-03-23 12-27-26l](https://user-images.githubusercontent.com/34026440/77324864-4b17a800-6d0f-11ea-8dfd-358a52b44d1a.png)


instead of: 
![Screenshot from 2020-03-23 12-27-26](https://user-images.githubusercontent.com/34026440/77324759-24f20800-6d0f-11ea-9d7f-518edca902f9.png)

**Comment by ColmMassey** [comment]
Sounds like it is worth just moving (not mirroring) the search box, in both modes, trying it and seeing how it flows.

**Comment by dtmakm27** [comment]
and there has been a search conducted since the last time the Directory was open, only the top Directory panel should open; (Otherwise there will be a disconnect between the co-ops visible on the map and those available for selection in the panel.)

Reading this a couple of times it confused me a bit. Let's say you open Australia:

![Screenshot from 2020-03-27 00-49-13](https://user-images.githubusercontent.com/34026440/77710050-e7b6a000-6fc4-11ea-973f-766799ab4693.png)


Then you search 888 and results from australia are shown

![Screenshot from 2020-03-27 00-50-23](https://user-images.githubusercontent.com/34026440/77710077-f8ffac80-6fc4-11ea-94b8-9ffd51dc834c.png)


Then you click back to Directory and it reveals the rest

![Screenshot from 2020-03-27 00-51-26](https://user-images.githubusercontent.com/34026440/77710118-1fbde300-6fc5-11ea-819b-9e92bdfd4b88.png)


and you end up again back at australia (instead of the top level)

Does that seem like what you imagined?




Also there's the question of whether clicking on show search, should reset the search.
E.g.
Search for asd
![Screenshot from 2020-03-27 00-54-21](https://user-images.githubusercontent.com/34026440/77710279-87742e00-6fc5-11ea-8293-00206d766826.png)


then clicking on search tab again reveals everything and displays a new search 
![Screenshot from 2020-03-27 00-54-57](https://user-images.githubusercontent.com/34026440/77710302-96f37700-6fc5-11ea-9d4e-e121d9fa8524.png)

Doing it this way it seems a bit more intuitive.

**Comment by dtmakm27** [comment]
https://dev.playground.solidarityeconomy.coop/

**Comment by ColmMassey** [comment]
> Does that seem like what you imagined?

The example you give works fine, but other examples may not. Hard to tell while there are big zoom/pan changes when you click the directory. Can you put up a version that disables all zoom/panning when you click back to the directory?

**Comment by dtmakm27** [comment]
done in latest version
http://dev.playground.solidarityeconomy.coop/
@ColmMassey

**Comment by ColmMassey** [comment]
The flow is feeling good now. I'll close this. Any future tweaks need new Issue.
