### ISSUE TITLE
Changes to config file

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#19]
- [x] Webpage title needs to be defined in the config file;
- [x] We need to be able to specify if the Database Panel is to be present;
- [ ] What aspects of the about/dataset page should be derived from somewhere else?;

**Comment by dtmakm27** [comment]
You can now show/hide the datasets panel with the following param showDatasetsPanel (e.g.  http://dev.playground.solidarityeconomy.coop/?showDatasetsPanel=false)

> What aspects of the about/dataset page should be derived from somewhere else?

The about tab basically currently takes in html and displays it. We could implement some basic customisation. I.e. include some options like aboutTitle and AboutDescription. Other than that I am not too sure what else we might include there


We could add a verboseDataset para to have a nice string name for each dataset (e.g. the verbose name of dotcoop would be .coop)
We can use the verbose names rather than the dataset name (handle dataset names like store1.asd.Lod.coopsuk.me.coopsk1 and display them as Coops UK)

Showing and hiding that tab is already implemented

Potentially short description for each dataset?

Other than that, in the next sprint when multiple datasets are a bit more stable we can open the dataset variable and have users input themselves which datasets they would like to see

**Comment by ColmMassey** [comment]
> Other than that, in the next sprint when multiple datasets are a bit more stable we can open the dataset variable and have users input themselves which datasets they would like to see

I think we can close this one. When we are taking a closer look at support of multiple data sets, we can look more closely at how we use these panels.
