### ISSUE TITLE
disableClusteringAtZoom not working as expected

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#43]
When testing disableClusteringAtZoom, setting it in URL I can't see any behaviour difference.

https://dev.oxford.solidarityeconomy.coop/map.html?disableClusteringAtZoom=1
https://dev.oxford.solidarityeconomy.coop/map.html?disableClusteringAtZoom=10
https://dev.oxford.solidarityeconomy.coop/map.html?disableClusteringAtZoom=17
https://dev.oxford.solidarityeconomy.coop/map.html?disableClusteringAtZoom=true
all behave the same and disable clustering always

https://dev.oxford.solidarityeconomy.coop/map.html?disableClusteringAtZoom=false
seems to be the default behaviour.

I wonder is there an easy, subtle way to display the current zoom level?

**Comment by ColmMassey** [comment]
Might just require chaning a boolean to an integer.

**Comment by wu-lee** [comment]
I've tried to replicate this. I see what you mean @ColmMassey in your examples - none of them are clustered. 

Except for disableClusteringAtZoom=true, that's clustered.

Digging down, as you guessed, it can be fixed by this change in `www/map-app/app/model/config_schema.js`:

```
     { id: 'disableClusteringAtZoom',
      descr: 'Defines the zoom level to stop clustering at (an integer; or false for off)',
       init: () => disableClusteringAtZoom,
       getter: 'getDisableClusteringAtZoom',
       setter: 'setDisableClusteringAtZoom',
-      type: types.boolean,
+      type: types.int,
     },
     { id: 'searchedFields',
```

In other words, this nominally integer parameter (although it allows a boolean) was being interpreted as a boolean. I've changed it to be integer and updated the documentation. We don't actually need the boolean case, as omitting this parameter (both from the app config and the query) turns off clustering, plus setting it to zero effectively disables it.

The new documentation says:

> Defines the zoom level above which to cluster pins; passed to Leaflet.markercluster plugin. Zero effectively disables clustering, as this is a fully zoomed-out, global map; most maps zoom in to level 18. If omitted, clustering is always off.  See: https://leaflet.github.io/Leaflet.markercluster/#other-options and https://leafletjs.com/examples/zoom-levels/

You ask:
> I wonder is there an easy, subtle way to display the current zoom level?

There seems to be- if you open the javascript console by hitting F12, you can see leaflet printing out the URLs of the map tiles it is loading. These URLs include the zoom level, so you can see the current zoom level (approximately, anyway).

**Comment by wu-lee** [comment]
I've not yet merged the fix onto the master branch. At some point, in coordination with @dtmakm27, will deploy this (and maybe other fixes) for review.
