### ISSUE TITLE
Map tiles not appearing

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#45]
It is not uncommon for the map tiles not to appear. It is not deteministic and can occur when doing different things. One common trigger path to induce is the following.

Open a map with a large data set, e.g. DotCoop.
Open the Directory. Select Argentina, then select Australia and then select Argentina, then select Australia again. 

It feels similar to the Marker Disappearing bug.
https://github.com/orgs/SolidarityEconomyAssociation/projects/5#card-36800109

![image](https://user-images.githubusercontent.com/1162642/79987563-7ecc2600-84a5-11ea-95ba-5b8f4489d97b.png)

**Comment by ColmMassey** [comment]
This happening a lot on new ICA map.

**Comment by dtmakm27** [comment]
UPDATE: 
Bug seems to occur mainly in Firefox 
Chrome does not seem to be affected as much (if at all)

**Comment by ColmMassey** [comment]
> Chrome does not seem to be affected as much (if at all)

Agreed, I have not replicated on Chrome.

**Comment by dtmakm27** [comment]
UPDATE 2: 
Seems to occur in different zoom levels (i.e. at maxZoom 10 and maxZoom: 17)

Also the packets with images are correctly recognised and loaded by the browser. I.e. files are cached and properly loaded in the DOM:
![image](https://user-images.githubusercontent.com/34026440/84520604-ba2be980-accb-11ea-8f2d-ed11fb05368d.png)

![image](https://user-images.githubusercontent.com/34026440/84520792-00814880-accc-11ea-8d0e-ec4b08249f96.png)


The problem comes about when firefox attempts to render the tile images, not in the communication layers (between the client (leaflet) and osm)

Note: the tile packets get cached (when you quickly zoom in/out you won't be downloading the packets again)

Leaflet (and firefox) can be forced to re-render the tiles when the size of the window is found to be invalid or upon a resize event

Reading the different issues that people are having with both leaflet and OSM in firefox rendering of tiles, seems to verify that resizing/triggering a re-rendering fixes the problem (99% sure about this, but no formal proof since firefox is a bit of a black box)

Assuming that the above is in-fact the case, retriggering the render event should not download new packets (i.e. performance stays somewhat the same) and should fix the disappearing tile issue

**Comment by dtmakm27** [comment]
UPDATE 3: 
Resizing back and forth (really quickly) and triggering an invalid window size seems to fix the tile rendering.
After the fix, I could not get the tiles to glitch and not render but it would be good to test it out 

I will deploy the map app and put in a message here, I think it also might have solved the disappearing marker issue.

Sadly there's no reliable way of testing this (because the issue is assumed to not be at a DOM level but at the browser rendering), i guess automation would be more complicated. I will put in a comment once i upload it and prompt you guys to test it out

**Comment by dtmakm27** [comment]
UPDATE 4:
@ColmMassey 
Fixed at: https://dev.ica.solidarityeconomy.coop/
Could you guys test it out as well to make sure it works on your ends? 
Seems to work on my phone as well.

**Comment by ColmMassey** [comment]
I can't seem to induce it after 10 minutes on Firefox!! :-)
