### ISSUE TITLE
How should we deal with sea-map configuration when are creating mini website themes?

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#58]
Note that when we have an instance of a sea-map in a mini website, parameters put in the websites url aren't passed to the sea-map instance.

So when we create a mini website theme, we need to ensure the parameters are set both in the iframe code for the sea-map in the main webpage, and the View Map in Fullscreen button link.   

Is there an easy way of the theme automatically pulling the documentation for the use of the parameters from Github?

**Comment by ColmMassey** [comment]
>Is there an easy way of the theme automatically pulling the documentation for the use of the parameters from Github? 

Would we need to submit the documentation with the rest of the code, or could we just pull it from the md file? @wu-lee

**Comment by wu-lee** [comment]
Currently docs are partly generated from the information in `config.js` - specifically those bits relating to the options.  There's an `npm` run script for regenerating the markdown documentation for that.

Is that useful? I'm not sure - it depends on the context of the documentation in Wordpress.

However, the theme could link or embed content from the sea-map repository, yes. It's hard to say more, I don't think I fully understand the issue here.
