### ISSUE TITLE
Explore options we have to improve the workflow for using search on mobile?

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#6]
With a small screen attempting to do keyword searches gets quite cumbersome. We may need to have the search box in a panel for mobile, rather than on the map. What other options are there?

**Comment by ColmMassey** [comment]
See https://github.com/SolidarityEconomyAssociation/sea-map/issues/14

**Comment by ColmMassey** [comment]
- [ ] On phones, the keyboard is triggered all the time, when it should only be triggered when you click/touch a search box.
- [ ] It seems impossible to search within a country on mobile, because the only way to get search after you have selected a country is to close the panel by clicking the x, which seems to move you back to the default search mode.

**Comment by dtmakm27** [comment]
On phones, the keyboard is triggered all the time, when it should only be triggered when you click/touch a search box.

It gets triggered on the directory tab as it auto-focuses on the little search mechanism for searching through the directory. Auto focus happens only in the background for bigger screens now (i.e. PCs)


 It seems impossible to search within a country on mobile, because the only way to get search after you have selected a country is to close the panel by clicking the x, which seems to move you back to the default search mode.

I am currently thinking of overlaying the top bars on the initiatives so you'd get something like this:
![Screenshot from 2020-03-29 21-55-02](https://user-images.githubusercontent.com/34026440/77863061-84707c00-7217-11ea-84ae-5ed040bcecc7.png)


(But with the coloring and everything else fixed)

**Comment by dtmakm27** [comment]
thoughts? @ColmMassey

**Comment by dtmakm27** [comment]
in the new version

**Comment by ColmMassey** [comment]
Works.
