### ISSUE TITLE
Scroll on directory panel lost.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#75]
When you open up a directory subpanel, that has more entries then can fit, the scroll feature is gone!
 I suspect this is a byporduct of the Safari patch that was recently uploaded.

This is urgent.
We should have tested it in the dev version before pushing to production.

**Comment by wu-lee** [comment]
Ok - I'll revert it on production now.

**Comment by wu-lee** [comment]
Ok, I've redeployed to `lod.directory.coop` using sea-map v0.1.46 (so prior to the Safari fix). Note this also loses the version in the popup which was added subsequently, but I suspect this doesn't matter so much.

**Comment by wu-lee** [comment]
Have spent over an hour looking for a workaround for this, without success.  This seems like it might be a bug/quirk of Safari/iOS and flexbox layout. I do find people saying they have similar problems.  I don't currently see any easy solutions, which don't require redesigning the stylesheet in a way which seems non-trivial. I suspect it may take a lot of research and testing to find something which works and hasn't broken something else.

iOS is tricky to debug because I don't have a Mac to connect to it - apparently this is how you are meant to do the kind of things Firefox and Chrome on the desktop can do by hitting F12.  So I can't use my usual tricks of tweaking the stylesheet the the developer console and watching what changes, live. I have to edit the code, redeploy, clear the browser cache in the settings, then reload.  This slows it all down massively.

The options see to be:
- live with the original layout bug for now
- and/or advise people not to use iOS/Safari
- allocate a fair amount of time to try and fix this as per above
- find someone with iOS / Safari experience who may already know how
- think of some other sort of hacky workaround? (although I can't currently think of one)

Looking at the git commit history, this design looks like it dates back to before the start of the sea-map project, back into open-data-and-maps, so this may have been lurking there for some time.

**Comment by ColmMassey** [comment]
>     * and/or advise people not to use iOS/Safari

It's not just Safari but also Chrome on IPhones, so essentially we would be saying it doesn't work on IPhones :-(

**Comment by ColmMassey** [comment]
We can close this as we have rolled back the Iphone 'fix' that induced it.

But I'm moving https://github.com/SolidarityEconomyAssociation/dotcoop-project/issues/9 into the active Kanban board.

**Comment by wu-lee** [comment]
@ColmMassey - revisited this, having had more experience with flexbox layouts, and having been poking around in the stylesheets for https://github.com/SolidarityEconomyAssociation/ica-project/issues/5 . I think I have a fix for the original iOS layout problem [here][1].

Tested for these bugs and found abesent on:
- iOS
  - Safari
  - Chrome
- OS X
  - Firefox
  - Chrome
  - Safari
- Linux
  - Firefox
  - Chrome

On iOS specifically, confirm that layout problem is gone, scrolling still works for me (although iPad scrolling is temperamental sometimes, it likes to pop up a virtual keyboard and scroll the whole web page). 

I can't test on Windows.

Sea-map doesn't seem to work on Firefox on Android at all, even without this fix: the data never loads. Don't have Chrome here to test.

The stylesheets are very hard to work with, and I suspect, contain a lot of crufty definitions and in general a more complicated design than it needs. I encountered encountered odd issues like the scrollbar for a hidden sidebar tab showing through the visible one (worked around, I think).  Overall it is hard to see what affects what, so fixing is a very empirical process, even before you start to think about bugs in different browser platforms. 

As such, I don't think I broke anything else, but just in case I'm not rolling this into any of our deployments yet, pending agreement with you about where & when to test it out. Also not yet mentioning it in the [original issue][1] until we've done this.

[1]: https://github.com/SolidarityEconomyAssociation/dotcoop-project/issues/9

**Comment by ColmMassey** [comment]
> I can't test on Windows.

Is there a version somewhere I can test on Windows?

**Comment by ColmMassey** [comment]
> Sea-map doesn't seem to work on Firefox on Android at all, even without this fix: the data never loads. Don't have Chrome here to test.

I am confused by what you mean here. What aspect of sea-map doesn't work on Firefox on Android? I use that all the time.

**Comment by wu-lee** [comment]
> Is there a version somewhere I can test on Windows?

It's not deployed anywhere public at the moment. I could try deploying on dev.dotcoop?

**Comment by wu-lee** [comment]
> > Sea-map doesn't seem to work on Firefox on Android at all, even without this fix: the data never loads. Don't have Chrome here to test.
> 
> I am confused by what you mean here. What aspect of sea-map doesn't work on Firefox on Android? I use that all the time.

For me, the page opens, and the spinner spins forever. This is on dev.newbridge and dev.ica

**Comment by ColmMassey** [comment]
> For me, the page opens, and the spinner spins forever. This is on dev.newbridge and dev.ica

I have just tested in 2 android phones. CoopsUK does take an age to load though. (30 seconds on worst phone with wifi. ) How big is the data download?

**Comment by ColmMassey** [comment]
> It's not deployed anywhere public at the moment. I could try deploying on dev.dotcoop?

Good one to test on. I'll ask iphone palls to test. How big is dotcoop download?

**Comment by wu-lee** [comment]
Co-ops UK: a CSV dump of the stock SPARQL output is 4.0MB. But the JSON dump is 11MB.

For DotCoop: CSV is 1.3MB, JSON is 4.2M

**Comment by ColmMassey** [comment]
Do you think it is the downloading or the unpacking in the browser that takes most of the time?

**Comment by wu-lee** [comment]
The downloading, I expect, but this is a guess. Parsing text is usually fast; however the mobile browser page will be chewing up quite lot of memory for the data, and this may have overheads.

**Comment by wu-lee** [comment]
sea-map 0.1.62 includes the fix, this is now deployed on https://dev.dotcoop.solidarityeconomy.coop/

**Comment by wu-lee** [comment]
@ColmMassey @dtmakm27 
A fix for this fix now deployed, same location (and same version, 0.1.62) to fix the problem introduced with the search field floating down the sidebar.  Also includes
- a fix for iOS/Safari, where the navigation arrows on the sidebar wrap, and stack one above the other. 
- and a fix for their size and alignment, which wasn't uniform with the other buttons
- and a fix for a clipped / rounded boundary on the search box (removed the default safari roundedness)

These fixed on a new `dev` branch, rather than on `master`, so they don't get included by accident on other sites.
