### ISSUE TITLE
Copy initiatives from sea-map to sea-map.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/sea-map#81]
Explore what it would take to be able to do the following. 

 - Select a group of co-ops/initiatives
 - Copy (as a list of those inititiaves' uris)
 - Open another sea-map instance
 - 'Import' these initiatives into this sea-map - Essentially treat this list of uris as if it is another referenced graph.

**Comment by wu-lee** [comment]
Does this need to be something you would do in a browser, or could it be something done in the terminal?

Editing the data in the browser via sea-map isn't currently possible. It would presumably need to trigger a sausage factory re-build, since the static and virtuoso linked data would need to be updated too.

**Comment by ColmMassey** [comment]
Not sure what you mean by 'in the terminal?'

It should be straight forward to copy a list of uris into the clipboard.

Then I imagine an option when you open the datasets panel to 'view other datasets', where you could paste in a list of co-op uris. SEA map then would need to query each of those uris individually to pull out the data required to add them to the local directory and display them on the map. We wouldn't need to do anything on the server. It would all be in the browser.
